sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  global:
    - secure: "fnqTJiQfPvE2MjmNqmiRXM7W9yCls00RjNgZu6OwRxCnOrpYqleVjyAfEKVwuI3KJAhSoeNNO6hLKEvMSMAtkSFOVFm+xelrcccD0haw2N+3Z3rywoAFMK6VA1WWOFPq1rsp/PlalBJaw9ljHogPBCla0BzRiHu59kXJSwe4NR8b63tXIq42jcG81p2slJFhz4rPbLyryHIYQ8j/1VBNUGCzJiStDtemtovwB60flWqYHAOq7w24XL1ShtLB7nmzLslqbogLcyYkK4Rw4RpvCRuevudB1Y9y3+4tEqu230z5NU4qOpn144zwTzEr2HzAt4tNSmPt4f8eyPT4/WpuDkY8tkxbWEz+1jDdhYGq042ItuNy1HULoXe3px7xwI2iwDG3aR6cKdGzlpAvIJzgAv4eCRxXNXRx77h1NEJY0WQKxOKsRQiphdmPemrH3z+75se8DgZKmuxKI5lj33WTNXzN2C7JM8ivtXQVS16PcpWvH2kIpaldGffOg+1b3HwLc+chvLj9mHLp9L7jej+LBGRA5BE1OYUGN9SAfbaPxW9zrZXCO/WH6+rW9eSZYOt8wJnmalQnAfGHTjBRZQYXar58WeDVOVSsAWMKEkSjD+N+dzNc7wO4sHHZfFnt1chwYS2/eYW64hNPW7ckO+pUycK0iIi1zfPATHRCnOQSCNY="
