sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  - secure: "koYmMi9PgL0TxADiBpqtDoFLLokq3HhIF4xbJpjNbZOitmVF19MYp5pLEBfhm/bYrife7zsdezfHwj2VIAEGRedeuBtJCPADmWzhoNin1NSkcynRDW9IXR75Lt4gDcOMX5zaAiRtHoplrkp2Fto7Kr82/DpXt67HyO3p+QtIDu/FjP2lLrf1KH+fuPTgoACvMaanzJLSkID1cv4bsB3aluwtKv3LVDv3Q6kuvZWFjO/khmeOswARbkV4vt9KP1p1NbtQAtjnsIMlE+FonF2SeYLnv33e9lSfzF4r4uRWw1//YZ1W+38QwV0K+c0hl9o93xBP7GayAuO2NHCFqykiPpHDA1ytIx8/3EY8QP4f6mmUP8wZFwXRxK9dJ7C3KvROtPN/F8w+E3hHtaN7rCwLRyrzfcO5XVZqeLODbpMUYTUaCl1RQxDpqcPf9L5YUPGC7OrkXk+wcluazmV7XPV7jryXpwCZs/9OS9JoiTOGW+QJrHjtiRl3vILKCwusECUJLA9qtt0LDd6QedsmvSDT8w5sZISzsjYGjJeFYZEjhMxHCTAKAMRYxBZp5pIa5xtmsUXbeHDj49NCPi8epA/kE66OySfdTfYQyLSm27e98q4gY/fzcBoxs+Ow3oSEIe4dhUh2x4QFDPPoYhCfIdphvCsPPvtHKTuYuFRqD61CIY="
