sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  secure: "lUeFbF5sVdV0yTk+JCRs06A2LxHJzb6q6Jx3gBlmkeEpMMAqk40EtVcyLsJvKykmPGII+PvC5uxXaivxS+9v4BaxELTb9wSE4rYD2u04kcPr/yqW9l9Hr0/Jf7KZw+RXh+bFE2Zzkp9tkpd7Oj00lnlHl+/KQvhQW484UKPqxg+ZIo++9k9y3gYH53WAifTZAkfBfc6Gh8RiSaOniMghRKUX0af7Hr1VGHSm/mtseKwPBruv4s1zeRxJowafQ+aAtP8Kyjc8iprDWFRbMXvI5OLuS5+xn9P/WhCNvM3/puIw8KXgWsncf61ooOt1Tx4c+kc1wUnEmRRmJ/YlR35Gp8SDJfX01D85L5aZw8O/YM6BEuKH56THT+bJPg32A8cygrXZ9kOpABN8jrZhqNiXZ/jhDTtssYgd1Bc+//OeJVxZZzo08S5FV8VS6NiN7/e8DVM1vNjknwWeADwSjbpCWJYund9LClePXPz2EZ8Rg6z6NHSB915g7+JVHZ8KQgjQcBPLMIMGmbUoacD0w2jw34I1St6jnKPw6ilPyRRDZppqsMJoH1wQd5j6HaHawB0Bt50A6DknImkDRWp7rOr88Zg+Bkd90ZKrooV913Tx8ltIsZ1QDP3II57DxSYbUzjqa7GhVbnuaqaatTKHyYGmw1IeFBu+EyCBEfCVuSinVzM="
