sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  - secure: "N6/4r4As6eTkjniLnbRHlKHPiwvWxArhItC8NxdiXmwKK9Kh3TwcXyHbfX7I4eGdImlOFghpk78If7xJTXrLVGbHkjzUkkO+8q6hYuHJniHZETEsNY3GCf7+z8vCgJf+/wlHGL6XWMpbrdK3b+UYkob96WGcptfUPrCsLRV1IEP7rX75nfUgcfy5DI3T2hKv955ME8VGsXCnFsQE7mi3uAfLcBkeUfVhzcT7KXQ0k/4GOm2O6+aFySpl5QcbVz3xBbte0XGmk67fptODD2MVDSbNnKbBB8l6Ni5nBoZ8qBb2Q/BWgSMT+ubKlI/JuucxJ/hZ1F0+uh+Aty2tgIAf05KratbhJOCdGDuGbaHL6PMZKo4G61kFKCph7BiLYWC+zIN/Mgp6lU241nVRwwy1SHqS/DtqaBWO1szHylk1Aeh6+3eCowDWG6xR6VPRWQjsGlkjGBgF+6kHKDLwQzzPe++gCriTdaz31LBgR/yE99ef1CYiyxJJWSEixOBBDJGkRlyAKHUDnXQPHqiQD9iNTCrL4f0HlXB/0GIVONkWFDaoIYCTxXWK8V4oAHq4gqwzXFfiYco73FZpeVB22Vg40u5xgO1RMpXzG0vsTi15w1/a8a7TAbYTxTx4eu56HvADlTqfdShFSYnw4T+h+ilnDOJjpEFqGnaGpwCGui+4G18="
