# Site settings
title: Srikrishnan Research Group
email: vs498@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the website for the Srikrishnan Research Group at Cornell BEE. We study the impact of dynamic environmental hazards, particularly those intensified by climate change, on infrastructure performance and management. We are interested in a broad range of applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
github:  srikrishnan-lab
office: 318 Riley-Robb Hall
department: Biological & Environmental Engineering
city: Ithaca, NY
zip: 14853-5701

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"

# logos and images
logo_group: /assets/img/logos/sea_level_rise_banner.png
logo_cornell: /assets/img/logos/cornell-reduced-red.svg

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
