# Site settings
title: Anderson Research Group @ Cornell BEE
email: cla28@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the website for the Srikrishnan Research Group at Cornell BEE. We study the impact of dynamic environmental hazards, particularly those intensified by climate change, on infrastructure performance and management. We are interested in a broad range of applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andersonenergylab-cornell.github.io" # the base hostname & protocol for your site
github:  andersonenergylab-cornell
office: 316 Riley-Robb Hall
department: Biological & Environmental Engineering
city: Ithaca, NY
zip: 14853-5701


# Build settings
markdown: kramdown

# Other options
permalink: /:year/:month/:title/
excerpt_separator: "<!--more-->"

# logos and images
logo_group: /assets/img/logos/sea_level_rise_banner.png
logo_cornell: /assets/img/logos/cornell-reduced-red.svg

# settings for deploy rake task
safe: False
lsi: False
username: andersonenergylab-cornell
repo: andersonenergylab-cornell.github.io
branch: master
destination: _site
production_url: https://andersonenergylab-cornell.github.io
source_url: https://github.com/andersonenergylab-cornell/andersonenergylab-cornell.github.io

plugins_dir: "_plugins"
plugins:
  - jekyll-scholar
  - jekyll-sitemap

exclude:
  - "scripts"
  - "README.md"
  - ".DS_Store"
  - "assets/less/"
  - "vendor"

scholar:
  style: american-geophysical-union
  source: publication_bib
  bibliography: library.bib
  bibliography_template: bib
  sort_by: date,year,month
  order: descending
  bibliography_list_tag: div
  bibliography_item_tag: div
  repository: publication_bib
